import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Shield, AlertTriangle, CheckCircle, Eye, Flag, Brain } from "lucide-react"

export function FraudDetection() {
  const fraudAlerts = [
    {
      id: "FR001",
      type: "Duplicate Application",
      pilgrimName: "Suspected: Musa Ibrahim",
      riskLevel: "High",
      confidence: 94,
      details: "Same passport number found in 2 different applications",
      status: "Under Investigation",
      timestamp: "2024-01-15 10:30 AM",
    },
    {
      id: "FR002",
      type: "Document Forgery",
      pilgrimName: "Suspected: Aisha Mohammed",
      riskLevel: "Medium",
      confidence: 78,
      details: "Medical certificate shows signs of digital manipulation",
      status: "Pending Review",
      timestamp: "2024-01-15 09:15 AM",
    },
    {
      id: "FR003",
      type: "Identity Mismatch",
      pilgrimName: "Suspected: Yusuf Ahmed",
      riskLevel: "Low",
      confidence: 65,
      details: "Photo similarity score below threshold",
      status: "Resolved",
      timestamp: "2024-01-14 04:20 PM",
    },
  ]

  const getRiskColor = (level: string) => {
    switch (level) {
      case "High":
        return "bg-red-100 text-red-800 border-red-200"
      case "Medium":
        return "bg-amber-100 text-amber-800 border-amber-200"
      case "Low":
        return "bg-blue-100 text-blue-800 border-blue-200"
      default:
        return "bg-gray-100 text-gray-800 border-gray-200"
    }
  }

  const getStatusColor = (status: string) => {
    switch (status) {
      case "Resolved":
        return "bg-green-100 text-green-800 border-green-200"
      case "Under Investigation":
        return "bg-red-100 text-red-800 border-red-200"
      case "Pending Review":
        return "bg-amber-100 text-amber-800 border-amber-200"
      default:
        return "bg-gray-100 text-gray-800 border-gray-200"
    }
  }

  return (
    <div className="space-y-6">
      {/* AI Fraud Detection Overview */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center">
            <Shield className="w-5 h-5 mr-2 text-red-600" />
            AI-Powered Fraud Detection System
          </CardTitle>
          <CardDescription>
            Advanced machine learning algorithms continuously monitor for suspicious activities
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-3 gap-4">
            <div className="text-center p-4 bg-red-50 rounded-lg border border-red-200">
              <AlertTriangle className="w-8 h-8 text-red-600 mx-auto mb-2" />
              <div className="text-2xl font-bold text-red-700">3</div>
              <div className="text-sm text-red-600">Active Alerts</div>
            </div>
            <div className="text-center p-4 bg-green-50 rounded-lg border border-green-200">
              <CheckCircle className="w-8 h-8 text-green-600 mx-auto mb-2" />
              <div className="text-2xl font-bold text-green-700">47</div>
              <div className="text-sm text-green-600">Cases Resolved</div>
            </div>
            <div className="text-center p-4 bg-blue-50 rounded-lg border border-blue-200">
              <Brain className="w-8 h-8 text-blue-600 mx-auto mb-2" />
              <div className="text-2xl font-bold text-blue-700">96.8%</div>
              <div className="text-sm text-blue-600">AI Accuracy</div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Fraud Alerts */}
      <Card>
        <CardHeader>
          <CardTitle>Fraud Detection Alerts</CardTitle>
          <CardDescription>Real-time alerts generated by AI fraud detection algorithms</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {fraudAlerts.map((alert) => (
              <Alert key={alert.id} className="border-l-4 border-l-red-500">
                <div className="flex items-start justify-between">
                  <div className="flex items-start space-x-3">
                    <Flag className="w-5 h-5 text-red-600 mt-1" />
                    <div className="flex-1">
                      <div className="flex items-center space-x-2 mb-2">
                        <h4 className="font-semibold">{alert.type}</h4>
                        <Badge variant="outline" className={getRiskColor(alert.riskLevel)}>
                          {alert.riskLevel} Risk
                        </Badge>
                        <Badge variant="outline" className={getStatusColor(alert.status)}>
                          {alert.status}
                        </Badge>
                      </div>
                      <AlertDescription className="mb-2">
                        <strong>{alert.pilgrimName}</strong> - {alert.details}
                      </AlertDescription>
                      <div className="flex items-center space-x-4 text-sm text-muted-foreground">
                        <span>Alert ID: {alert.id}</span>
                        <span>Confidence: {alert.confidence}%</span>
                        <span>{alert.timestamp}</span>
                      </div>
                    </div>
                  </div>
                  <div className="flex space-x-2">
                    <Button size="sm" variant="outline">
                      <Eye className="w-4 h-4 mr-1" />
                      Investigate
                    </Button>
                    <Button size="sm" variant="outline">
                      Resolve
                    </Button>
                  </div>
                </div>
              </Alert>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
